# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
