# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('TypeThreat_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('wikipedia_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
