# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('threatDetail_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('location_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('source_score', models.CharField(max_length=100)),
                ('detection_date', models.CharField(max_length=100)),
                ('damage_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('detection_id', models.IntegerField()),
                ('date_time', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='threat',
            old_name='TypeThreat_id',
            new_name='typeThreat_id',
        ),
        migrations.RemoveField(
            model_name='threatdetail',
            name='code',
        ),
        migrations.RemoveField(
            model_name='threatdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='threatdetail',
            name='expiracion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatdetail',
            name='rango_alcance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatdetail',
            name='threat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatdetail',
            name='typeCrop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
