# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_auto_20160822_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.IntegerField()),
                ('content', models.CharField(max_length=600)),
            ],
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='detection_date',
            new_name='date',
        ),
    ]
