# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_auto_20160823_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='source_score',
        ),
        migrations.AlterField(
            model_name='detection',
            name='damage_level',
            field=models.IntegerField(max_length=100),
        ),
    ]
