# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_auto_20160823_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='movil_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
