# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_detection_movil_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='detection_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='note',
            name='object_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detection',
            name='damage_level',
            field=models.IntegerField(),
        ),
    ]
