# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0006_auto_20160824_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='detection_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='picture',
            name='object_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='content',
            field=models.FileField(upload_to=b''),
        ),
    ]
