# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0007_auto_20160824_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='content',
            field=models.ImageField(upload_to=b''),
        ),
    ]
