# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_auto_20160824_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='content',
        ),
        migrations.AddField(
            model_name='detection',
            name='activity_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=2, upload_to='img'),
            preserve_default=False,
        ),
    ]
