# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0009_auto_20160825_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
