# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0010_note_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=100)),
                ('date_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DetectionDetail',
        ),
    ]
