# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0012_auto_20160930_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
