# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0013_auto_20160930_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
