# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0014_threat_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='code',
            field=models.IntegerField(),
        ),
    ]
