# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0015_auto_20161006_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='activity_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='detection',
            name='movil_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='detection',
            name='threatDetail_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='object_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='seen',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
