# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0018_auto_20161022_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='seen',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
    ]
