# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0019_auto_20161025_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='source',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
