# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
