# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushes', '0002_auto_20160906_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
    ]
