# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('parcel_id', models.IntegerField()),
                ('type_crop_id', models.IntegerField()),
                ('campaign', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('movil_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('movil_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('lat_center', models.CharField(max_length=100)),
                ('long_center', models.CharField(max_length=100)),
                ('movil_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_user', models.IntegerField()),
                ('mobile_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
