# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='lat_center',
            new_name='center_lat',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='long_center',
            new_name='center_long',
        ),
    ]
