# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo', '0002_auto_20160829_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='movil_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='parcel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='movil_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='farm_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='movil_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
